[package]
name = "cargo_manifest"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/testnet" }

[addresses]
cargo_manifest = "0x0"

[dev-dependencies]
[dev-addresses]
